name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USER}}
        password: ${{secrets.DOCKER_HUB_PWD}}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: pkid/dogsitter:latest
